redirects:
  getting-started/overview: product-tour/navigation.md
  getting-started/import: content-creation/import.md
  getting-started/git-sync: product-tour/git-sync/README.md
  getting-started/git-sync/bi-directional-git-integration: product-tour/git-sync/bi-directional-git-integration.md
  getting-started/git-sync/enabling-github-sync: product-tour/git-sync/enabling-github-sync.md
  getting-started/git-sync/enabling-gitlab-sync: product-tour/git-sync/enabling-gitlab-sync.md
  getting-started/git-sync/content-configuration: product-tour/git-sync/content-configuration.md
  getting-started/git-sync/github-pull-request-preview: product-tour/git-sync/github-pull-request-preview.md
  integrations/git-sync/github-pull-request-preview: product-tour/git-sync/github-pull-request-preview.md
  getting-started/git-sync/commits: product-tour/git-sync/commits.md
  getting-started/git-sync/monorepos: product-tour/git-sync/monorepos.md
  getting-started/git-sync/troubleshooting: product-tour/git-sync/troubleshooting.md
  getting-started/content-structure: content-creation/content-structure/README.md
  getting-started/content-structure/what-is-a-space: content-creation/content-structure/what-is-a-space.md
  getting-started/content-structure/content-structure: content-creation/content-structure/content-in-a-space.md
  getting-started/content-structure/what-is-a-collection: content-creation/content-structure/what-is-a-collection.md
  getting-started/collaboration: collaboration/collaboration/README.md
  getting-started/collaboration/live-edits: collaboration/collaboration/live-edits.md
  getting-started/collaboration/change-requests: collaboration/collaboration/change-requests.md
  getting-started/collaboration/comments-discussion: collaboration/comments-discussion.md
  getting-started/publishing: publishing/publishing/README.md
  getting-started/publishing/space-publishing: publishing/publishing/space-publishing.md
  getting-started/publishing/collection-publishing: publishing/publishing/collection-publishing.md
  getting-started/publishing/share-links: publishing/publishing/share-links.md
  tour/quick-find: product-tour/quick-find.md
  tour/editor: content-creation/editor/README.md
  tour/editor/rich-text: content-creation/editor/rich-text.md
  tour/editor/blocks: content-creation/blocks/README.md
  tour/editor/blocks/paragraph: content-creation/blocks/paragraph.md
  tour/editor/blocks/cards: content-creation/blocks/cards.md
  tour/editor/blocks/heading: content-creation/blocks/heading.md
  tour/editor/blocks/unordered-list: content-creation/blocks/unordered-list.md
  tour/editor/blocks/ordered-list: content-creation/blocks/ordered-list.md
  tour/editor/blocks/task-list: content-creation/blocks/task-list.md
  tour/editor/blocks/hint: content-creation/blocks/hint.md
  tour/editor/blocks/quote: content-creation/blocks/quote.md
  tour/editor/blocks/code-block: content-creation/blocks/code-block.md
  tour/editor/blocks/insert-files: content-creation/blocks/insert-files.md
  tour/editor/blocks/insert-images: content-creation/blocks/insert-images.md
  tour/editor/blocks/embed-a-url: content-creation/blocks/embed-a-url.md
  tour/editor/blocks/table: content-creation/blocks/table.md
  tour/editor/blocks/tabs: content-creation/blocks/tabs.md
  tour/editor/blocks/expandable: content-creation/blocks/expandable.md
  tour/editor/blocks/drawing: content-creation/blocks/drawing.md
  tour/editor/blocks/math-and-tex: content-creation/blocks/math-and-tex.md
  tour/editor/blocks/api-method: content-creation/blocks/api-method.md
  tour/editor/blocks/openapi: content-creation/blocks/openapi.md
  tour/editor/blocks/page-link: content-creation/blocks/page-link.md
  tour/editor/inline: content-creation/editor/inline/README.md
  tour/editor/inline/image: content-creation/editor/inline/image.md
  tour/editor/inline/emoji: content-creation/editor/inline/emoji.md
  tour/editor/inline/link: content-creation/editor/inline/link.md
  tour/editor/inline/math-and-tex: content-creation/editor/inline/math-and-tex.md
  tour/editor/formatting: content-creation/editor/formatting.md
  tour/editor/markdown: content-creation/editor/markdown.md
  tour/customization: publishing/customization/README.md
  tour/customization/space-customization: publishing/customization/space-customization.md
  tour/customization/collection-customization: publishing/customization/collection-customization.md
  tour/member-management: account-management/member-management/README.md
  tour/member-management/invite-members-to-your-organization: collaboration/invite-members-to-your-organization/README.md
  tour/member-management/roles: collaboration/invite-members-to-your-organization/roles.md
  tour/member-management/teams: account-management/member-management/teams.md
  tour/member-management/permissions-and-inheritance: account-management/member-management/permissions-and-inheritance.md
  tour/pdf-export: publishing/publishing/pdf-export.md
  tour/activity-history: content-creation/activity-history.md
  tour/insights: publishing/insights.md
  tour/notifications: collaboration/notifications.md
  tour/internationalization: publishing/internationalization.md
  tour/keyboard-shortcuts: product-tour/keyboard-shortcuts.md
  resources/keyboard-shortcuts: product-tour/keyboard-shortcuts.md
  tour/seo: publishing/seo.md
  advanced-guides/custom-domain: publishing/custom-domain/README.md
  advanced-guides/custom-domain/choose: publishing/custom-domain/choose.md
  advanced-guides/custom-domain/location: publishing/custom-domain/location.md
  advanced-guides/custom-domain/initiate: publishing/custom-domain/initiate/README.md
  advanced-guides/custom-domain/initiate/organization-level-custom-domain: publishing/custom-domain/initiate/organization-level-custom-domain.md
  advanced-guides/custom-domain/initiate/collection-level-custom-domain: publishing/custom-domain/initiate/collection-level-custom-domain.md
  advanced-guides/custom-domain/initiate/space-level-custom-domain: publishing/custom-domain/initiate/space-level-custom-domain.md
  advanced-guides/custom-domain/configure-dns: publishing/custom-domain/configure-dns.md
  advanced-guides/custom-domain/finalize: publishing/custom-domain/finalize.md
  advanced-guides/custom-domain/troubleshooting: publishing/custom-domain/troubleshooting.md
  advanced-guides/advanced-sharing-and-security: product-tour/sso-and-saml/README.md
  advanced-guides/advanced-sharing-and-security/sso-and-saml: product-tour/sso-and-saml/README.md
  advanced-guides/advanced-sharing-and-security/saml: product-tour/sso-and-saml/saml/README.md
  advanced-guides/advanced-sharing-and-security/scim-and-directory-sync: product-tour/sso-and-saml/scim-and-directory-sync/README.md
  advanced-guides/advanced-sharing-and-security/visitor-authentication: publishing/visitor-authentication.md
  advanced-guides/integrations: product-tour/integrations/README.md
  advanced-guides/integrations/integrations-faq: product-tour/integrations/integrations-faq.md
  advanced-guides/integrations/install-an-integration: product-tour/integrations/install-an-integration.md
  advanced-guides/integrations/arcade: product-tour/integrations/arcade/README.md
  advanced-guides/integrations/arcade/configure-the-arcade-integration: product-tour/integrations/arcade/configure.md
  advanced-guides/integrations/fathom: product-tour/integrations/fathom/README.md
  advanced-guides/integrations/fathom/configure-the-fathom-integration: product-tour/integrations/fathom/configure.md
  advanced-guides/integrations/figma: product-tour/integrations/figma/README.md
  advanced-guides/integrations/figma/configure-the-figma-integration: product-tour/integrations/figma/configure.md
  advanced-guides/integrations/google-analytics: product-tour/integrations/google-analytics/README.md
  advanced-guides/integrations/google-analytics/configure-the-google-analytics-integration: product-tour/integrations/google-analytics/configure.md
  advanced-guides/integrations/intercom: product-tour/integrations/intercom/README.md
  advanced-guides/integrations/inter: product-tour/integrations/intercom/configure.md
  advanced-guides/integrations/jira: product-tour/integrations/jira/README.md
  advanced-guides/integrations/jira/configure-the-jira-integration: product-tour/integrations/jira/configure.md
  advanced-guides/integrations/linear: product-tour/integrations/linear/README.md
  advanced-guides/integrations/linear/configure-the-integration: product-tour/integrations/linear/configure.md
  advanced-guides/integrations/mailchimp: product-tour/integrations/mailchimp/README.md
  advanced-guides/integrations/mailchimp/configure-the-mailchimp-integration: product-tour/integrations/mailchimp/configure.md
  advanced-guides/integrations/mermaid: product-tour/integrations/mermaid/README.md
  advanced-guides/integrations/mermaid/configure-the-mermaid-integration: product-tour/integrations/mermaid/configure.md
  advanced-guides/integrations/plausible: product-tour/integrations/plausible/README.md
  advanced-guides/integrations/plausible/configure-the-plausible-integration: product-tour/integrations/plausible/configure.md
  advanced-guides/integrations/runkit: product-tour/integrations/runkit/README.md
  advanced-guides/integrations/runkit/configure-the-runkit-integration: product-tour/integrations/runkit/configure.md
  advanced-guides/integrations/segment: product-tour/integrations/segment/README.md
  advanced-guides/integrations/segment/configure-the-integration: product-tour/integrations/segment/configure.md
  advanced-guides/integrations/segment/gitbook-segment-event: product-tour/integrations/segment/event.md
  advanced-guides/integrations/sentry: product-tour/integrations/sentry/README.md
  advanced-guides/integrations/sentry/configure-the-sentry-integration: product-tour/integrations/sentry/configure.md
  advanced-guides/integrations/slack: product-tour/integrations/slack/README.md
  advanced-guides/integrations/slack/configure-the-slack-integration: product-tour/integrations/slack/configure.md
  billing-and-admin/account-settings: account-management/account-settings.md
  billing-and-admin/plans: account-management/plans/README.md
  billing-and-admin/plans/organization-management: account-management/organization-management.md
  billing-and-admin/plans/free-trial: account-management/plans/README.md
  billing-and-admin/plans/non-profit-open-source-plan: account-management/plans/apply-for-the-non-profit-open-source-plan.md
  billing-and-admin/plans/billing-policy: account-management/billing-faq/billing-policy.md
  billing-and-admin/plans/cancelling-a-plan: account-management/billing-faq/cancelling-a-plan.md
  troubleshooting/faqs: faq/faqs.md
  troubleshooting/hard-refresh: faq/hard-refresh.md
  troubleshooting/report-bugs: faq/report-bugs.md
  troubleshooting/connectivity-issues: faq/connectivity-issues.md
  troubleshooting/support: faq/support.md
  features/import: content-creation/import.md
  snippets-and-content-insights/overview: snippets-and-insights/overview.md
  snippets-and-content-insights/snippets: snippets-and-insights/snippets-beta.md
  snippets-and-content-insights/snippets-beta: snippets-and-insights/snippets-beta.md
  snippets-and-content-insights/insights: snippets-and-insights/insights.md
  content-editor/editing-content/rich-text: content-editor/editing-content/inline.md
  content-editor/searching-your-content/lens: content-editor/searching-your-content/gitbook-ai.md
  collaboration/share/space-publishing: collaboration/share/share-a-space.md
  collaboration/share/collection-publishing: collaboration/share/share-a-collection.md
